// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: scan.proto

// https://cloud.google.com/apis/design/versioning

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stage int32

const (
	Stage_STAGE_INIT Stage = 0
	Stage_STAGE_RUN  Stage = 1
	Stage_STAGE_FINI Stage = 2
)

// Enum value maps for Stage.
var (
	Stage_name = map[int32]string{
		0: "STAGE_INIT",
		1: "STAGE_RUN",
		2: "STAGE_FINI",
	}
	Stage_value = map[string]int32{
		"STAGE_INIT": 0,
		"STAGE_RUN":  1,
		"STAGE_FINI": 2,
	}
)

func (x Stage) Enum() *Stage {
	p := new(Stage)
	*p = x
	return p
}

func (x Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_scan_proto_enumTypes[0].Descriptor()
}

func (Stage) Type() protoreflect.EnumType {
	return &file_scan_proto_enumTypes[0]
}

func (x Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stage.Descriptor instead.
func (Stage) EnumDescriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{0}
}

type Command int32

const (
	Command_CMD_RETR Command = 0
	Command_CMD_QUIT Command = 1
)

// Enum value maps for Command.
var (
	Command_name = map[int32]string{
		0: "CMD_RETR",
		1: "CMD_QUIT",
	}
	Command_value = map[string]int32{
		"CMD_RETR": 0,
		"CMD_QUIT": 1,
	}
)

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}

func (x Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command) Descriptor() protoreflect.EnumDescriptor {
	return file_scan_proto_enumTypes[1].Descriptor()
}

func (Command) Type() protoreflect.EnumType {
	return &file_scan_proto_enumTypes[1]
}

func (x Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command.Descriptor instead.
func (Command) EnumDescriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{1}
}

type C2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         Stage                  `protobuf:"varint,1,opt,name=stage,proto3,enum=amaas.scan.v1.Stage" json:"stage,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	RsSize        uint64                 `protobuf:"varint,3,opt,name=rs_size,json=rsSize,proto3" json:"rs_size,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,5,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Trendx        bool                   `protobuf:"varint,6,opt,name=trendx,proto3" json:"trendx,omitempty"`
	FileSha1      string                 `protobuf:"bytes,7,opt,name=file_sha1,json=fileSha1,proto3" json:"file_sha1,omitempty"`
	FileSha256    string                 `protobuf:"bytes,8,opt,name=file_sha256,json=fileSha256,proto3" json:"file_sha256,omitempty"`
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Bulk          bool                   `protobuf:"varint,10,opt,name=bulk,proto3" json:"bulk,omitempty"`
	SpnFeedback   bool                   `protobuf:"varint,11,opt,name=spn_feedback,json=spnFeedback,proto3" json:"spn_feedback,omitempty"`
	Verbose       bool                   `protobuf:"varint,12,opt,name=verbose,proto3" json:"verbose,omitempty"`
	ActiveContent bool                   `protobuf:"varint,13,opt,name=active_content,json=activeContent,proto3" json:"active_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S) Reset() {
	*x = C2S{}
	mi := &file_scan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S) ProtoMessage() {}

func (x *C2S) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S.ProtoReflect.Descriptor instead.
func (*C2S) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{0}
}

func (x *C2S) GetStage() Stage {
	if x != nil {
		return x.Stage
	}
	return Stage_STAGE_INIT
}

func (x *C2S) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *C2S) GetRsSize() uint64 {
	if x != nil {
		return x.RsSize
	}
	return 0
}

func (x *C2S) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *C2S) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *C2S) GetTrendx() bool {
	if x != nil {
		return x.Trendx
	}
	return false
}

func (x *C2S) GetFileSha1() string {
	if x != nil {
		return x.FileSha1
	}
	return ""
}

func (x *C2S) GetFileSha256() string {
	if x != nil {
		return x.FileSha256
	}
	return ""
}

func (x *C2S) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *C2S) GetBulk() bool {
	if x != nil {
		return x.Bulk
	}
	return false
}

func (x *C2S) GetSpnFeedback() bool {
	if x != nil {
		return x.SpnFeedback
	}
	return false
}

func (x *C2S) GetVerbose() bool {
	if x != nil {
		return x.Verbose
	}
	return false
}

func (x *C2S) GetActiveContent() bool {
	if x != nil {
		return x.ActiveContent
	}
	return false
}

type S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         Stage                  `protobuf:"varint,1,opt,name=stage,proto3,enum=amaas.scan.v1.Stage" json:"stage,omitempty"`
	Cmd           Command                `protobuf:"varint,2,opt,name=cmd,proto3,enum=amaas.scan.v1.Command" json:"cmd,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int32                  `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	Result        string                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	BulkOffset    []int32                `protobuf:"varint,6,rep,packed,name=bulk_offset,json=bulkOffset,proto3" json:"bulk_offset,omitempty"`
	BulkLength    []int32                `protobuf:"varint,7,rep,packed,name=bulk_length,json=bulkLength,proto3" json:"bulk_length,omitempty"`
	SessionId     string                 `protobuf:"bytes,8,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_scan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{1}
}

func (x *S2C) GetStage() Stage {
	if x != nil {
		return x.Stage
	}
	return Stage_STAGE_INIT
}

func (x *S2C) GetCmd() Command {
	if x != nil {
		return x.Cmd
	}
	return Command_CMD_RETR
}

func (x *S2C) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *S2C) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *S2C) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *S2C) GetBulkOffset() []int32 {
	if x != nil {
		return x.BulkOffset
	}
	return nil
}

func (x *S2C) GetBulkLength() []int32 {
	if x != nil {
		return x.BulkLength
	}
	return nil
}

func (x *S2C) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_scan_proto protoreflect.FileDescriptor

const file_scan_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"scan.proto\x12\ramaas.scan.v1\"\xf7\x02\n" +
	"\x03C2S\x12*\n" +
	"\x05stage\x18\x01 \x01(\x0e2\x14.amaas.scan.v1.StageR\x05stage\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x17\n" +
	"\ars_size\x18\x03 \x01(\x04R\x06rsSize\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05chunk\x18\x05 \x01(\fR\x05chunk\x12\x16\n" +
	"\x06trendx\x18\x06 \x01(\bR\x06trendx\x12\x1b\n" +
	"\tfile_sha1\x18\a \x01(\tR\bfileSha1\x12\x1f\n" +
	"\vfile_sha256\x18\b \x01(\tR\n" +
	"fileSha256\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12\x12\n" +
	"\x04bulk\x18\n" +
	" \x01(\bR\x04bulk\x12!\n" +
	"\fspn_feedback\x18\v \x01(\bR\vspnFeedback\x12\x18\n" +
	"\averbose\x18\f \x01(\bR\averbose\x12%\n" +
	"\x0eactive_content\x18\r \x01(\bR\ractiveContent\"\x84\x02\n" +
	"\x03S2C\x12*\n" +
	"\x05stage\x18\x01 \x01(\x0e2\x14.amaas.scan.v1.StageR\x05stage\x12(\n" +
	"\x03cmd\x18\x02 \x01(\x0e2\x16.amaas.scan.v1.CommandR\x03cmd\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x05R\x06length\x12\x16\n" +
	"\x06result\x18\x05 \x01(\tR\x06result\x12\x1f\n" +
	"\vbulk_offset\x18\x06 \x03(\x05R\n" +
	"bulkOffset\x12\x1f\n" +
	"\vbulk_length\x18\a \x03(\x05R\n" +
	"bulkLength\x12\x1d\n" +
	"\n" +
	"session_id\x18\b \x01(\tR\tsessionId*6\n" +
	"\x05Stage\x12\x0e\n" +
	"\n" +
	"STAGE_INIT\x10\x00\x12\r\n" +
	"\tSTAGE_RUN\x10\x01\x12\x0e\n" +
	"\n" +
	"STAGE_FINI\x10\x02*%\n" +
	"\aCommand\x12\f\n" +
	"\bCMD_RETR\x10\x00\x12\f\n" +
	"\bCMD_QUIT\x10\x012;\n" +
	"\x04Scan\x123\n" +
	"\x03Run\x12\x12.amaas.scan.v1.C2S\x1a\x12.amaas.scan.v1.S2C\"\x00(\x010\x01B3\n" +
	"\x1dcom.trend.cloudone.amaas.scanZ\x12amaas/scanner/baseb\x06proto3"

var (
	file_scan_proto_rawDescOnce sync.Once
	file_scan_proto_rawDescData []byte
)

func file_scan_proto_rawDescGZIP() []byte {
	file_scan_proto_rawDescOnce.Do(func() {
		file_scan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scan_proto_rawDesc), len(file_scan_proto_rawDesc)))
	})
	return file_scan_proto_rawDescData
}

var file_scan_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_scan_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_scan_proto_goTypes = []any{
	(Stage)(0),   // 0: amaas.scan.v1.Stage
	(Command)(0), // 1: amaas.scan.v1.Command
	(*C2S)(nil),  // 2: amaas.scan.v1.C2S
	(*S2C)(nil),  // 3: amaas.scan.v1.S2C
}
var file_scan_proto_depIdxs = []int32{
	0, // 0: amaas.scan.v1.C2S.stage:type_name -> amaas.scan.v1.Stage
	0, // 1: amaas.scan.v1.S2C.stage:type_name -> amaas.scan.v1.Stage
	1, // 2: amaas.scan.v1.S2C.cmd:type_name -> amaas.scan.v1.Command
	2, // 3: amaas.scan.v1.Scan.Run:input_type -> amaas.scan.v1.C2S
	3, // 4: amaas.scan.v1.Scan.Run:output_type -> amaas.scan.v1.S2C
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_scan_proto_init() }
func file_scan_proto_init() {
	if File_scan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scan_proto_rawDesc), len(file_scan_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scan_proto_goTypes,
		DependencyIndexes: file_scan_proto_depIdxs,
		EnumInfos:         file_scan_proto_enumTypes,
		MessageInfos:      file_scan_proto_msgTypes,
	}.Build()
	File_scan_proto = out.File
	file_scan_proto_goTypes = nil
	file_scan_proto_depIdxs = nil
}
